# Generated by Django 5.2.4 on 2025-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchaseitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='product_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
