# Generated by Django 5.2.5 on 2025-08-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='enter your description here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.TextField(default='Enter the location of your store', null=True),
        ),
    ]
