# Generated by Django 5.2.4 on 2025-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_description_alter_store_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
